# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [2]:
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [9]:
print(np.__version__)
np.show_config()


2.5.3
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.44.35228",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.3.0",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.44.35228",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.34.106.0",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-sp8l_b7i/cp314-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include",
      

c:\Users\anita\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [ ]:
# 1. 
a = np.random.random((2,3,5))

# 2. 
a = np.random.rand(2,3,5)

# 3. this lets you define the range
a = np.random.uniform(10,20,(2,3,5))

# 4.
a = np.random.sample((2,3,5))


[[[0.88555985 0.38675244 0.11387016 0.96185554 0.51970052]
  [0.22519205 0.55973216 0.66337572 0.81302182 0.28779938]
  [0.28040912 0.03993299 0.57908005 0.76479479 0.06008586]]

 [[0.41777928 0.93412836 0.7818784  0.9672617  0.60379409]
  [0.47957168 0.02326863 0.05158199 0.93754894 0.96414977]
  [0.73782352 0.48097485 0.83941605 0.67073176 0.39235734]]]



### 4. Print a.


In [28]:
### [your code here]
print(a)

[[[0.88555985 0.38675244 0.11387016 0.96185554 0.51970052]
  [0.22519205 0.55973216 0.66337572 0.81302182 0.28779938]
  [0.28040912 0.03993299 0.57908005 0.76479479 0.06008586]]

 [[0.41777928 0.93412836 0.7818784  0.9672617  0.60379409]
  [0.47957168 0.02326863 0.05158199 0.93754894 0.96414977]
  [0.73782352 0.48097485 0.83941605 0.67073176 0.39235734]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [30]:
b = np.ones((5,2,3))


### 6. Print b.


In [31]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [33]:
# bu using .size :  a and b have same size but different shapes. 
print(a.size)
print(b.size)

30
30



### 8. Are you able to add a and b? Why or why not?


In [ ]:
a.shape == b.shape
#No we cannot because there size is same but there shape is different. 

False



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [87]:
c = np.transpose(b,(1,2,0))
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [ ]:
# NumPy performs element-by-element addition.
d = a + c
print(d)

(2, 3, 5)
(5, 2, 3)
(2, 3, 5)
[[[1.88555985 1.38675244 1.11387016 1.96185554 1.51970052]
  [1.22519205 1.55973216 1.66337572 1.81302182 1.28779938]
  [1.28040912 1.03993299 1.57908005 1.76479479 1.06008586]]

 [[1.41777928 1.93412836 1.7818784  1.9672617  1.60379409]
  [1.47957168 1.02326863 1.05158199 1.93754894 1.96414977]
  [1.73782352 1.48097485 1.83941605 1.67073176 1.39235734]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [ ]:
print(f"a:\n {a}")
print(f"d:\n {d}")

# c was created from tranposing b: and b was created from b = np.ones((5, 2, 3)), so every value in c is 1s 
# So every value in d is exactly 1 greater than the corresponding value in a.   e.g: 0.4  +  1  =  1.4

a:
 [[[0.88555985 0.38675244 0.11387016 0.96185554 0.51970052]
  [0.22519205 0.55973216 0.66337572 0.81302182 0.28779938]
  [0.28040912 0.03993299 0.57908005 0.76479479 0.06008586]]

 [[0.41777928 0.93412836 0.7818784  0.9672617  0.60379409]
  [0.47957168 0.02326863 0.05158199 0.93754894 0.96414977]
  [0.73782352 0.48097485 0.83941605 0.67073176 0.39235734]]]
d:
 [[[1.88555985 1.38675244 1.11387016 1.96185554 1.51970052]
  [1.22519205 1.55973216 1.66337572 1.81302182 1.28779938]
  [1.28040912 1.03993299 1.57908005 1.76479479 1.06008586]]

 [[1.41777928 1.93412836 1.7818784  1.9672617  1.60379409]
  [1.47957168 1.02326863 1.05158199 1.93754894 1.96414977]
  [1.73782352 1.48097485 1.83941605 1.67073176 1.39235734]]]



### 12. Multiply a and c. Assign the result to e.


In [46]:
e = a * c
print(e)

[[[0.88555985 0.38675244 0.11387016 0.96185554 0.51970052]
  [0.22519205 0.55973216 0.66337572 0.81302182 0.28779938]
  [0.28040912 0.03993299 0.57908005 0.76479479 0.06008586]]

 [[0.41777928 0.93412836 0.7818784  0.9672617  0.60379409]
  [0.47957168 0.02326863 0.05158199 0.93754894 0.96414977]
  [0.73782352 0.48097485 0.83941605 0.67073176 0.39235734]]]




### 13. Does e equal to a? Why or why not?


In [ ]:
# c contains only 1s as it comes from b = np.ones()
# e will contains exactly the same values as a,  
# a x c =  a × 1
print(e==a)



[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [53]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(f"max:  {d_max}")
print(f"min:  {d_min}")
print(f"mean: {d_mean}")

max:  1.9672616962736234
min:  1.023268633989864
mean: 1.5474476267357775



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [78]:
f = np.empty((2,3,5))




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [77]:
d_min = d.min()
d_max = d.max()
d_mean = d.mean()

f = np.empty((2, 3, 5))

for i in range(2):
    for j in range(3):
        for k in range(5):
            if d[i, j, k] == d_min:
                f[i, j, k] = 0
            elif d[i, j, k] < d_mean:
                f[i, j, k] = 25
            elif d[i, j, k] == d_mean:
                f[i, j, k] = 50
            elif d[i, j, k] < d_max:
                f[i, j, k] = 75
            else:
                f[i, j, k] = 100

print(f)

[[[ 75.  25.  25.  75.  25.]
  [ 25.  75.  75.  75.  25.]
  [ 25.  25.  75.  75.  25.]]

 [[ 25.  75.  75. 100.  75.]
  [ 25.   0.  25.  75.  75.]
  [ 75.  25.  75.  75.  25.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [79]:
print(f"d:\n{d}")
print(f"f:\n{f}")

d:
[[[1.88555985 1.38675244 1.11387016 1.96185554 1.51970052]
  [1.22519205 1.55973216 1.66337572 1.81302182 1.28779938]
  [1.28040912 1.03993299 1.57908005 1.76479479 1.06008586]]

 [[1.41777928 1.93412836 1.7818784  1.9672617  1.60379409]
  [1.47957168 1.02326863 1.05158199 1.93754894 1.96414977]
  [1.73782352 1.48097485 1.83941605 1.67073176 1.39235734]]]
f:
[[[ 75.  25.  25.  75.  25.]
  [ 25.  75.  75.  75.  25.]
  [ 25.  25.  75.  75.  25.]]

 [[ 25.  75.  75. 100.  75.]
  [ 25.   0.  25.  75.  75.]
  [ 75.  25.  75.  75.  25.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [ ]:
# A → minimum
# B → below mean
# C → mean
# D → above mean
# E → maximum 

f = [] # clear f from old values

for i in range(2):
    block = []

    for j in range(3):
        row = []

        for k in range(5):
            value = d[i, j, k]

            if value == d_min:
                row.append("A")
            elif value < d_mean:
                row.append("B")
            elif value == d_mean:
                row.append("C")
            elif value < d_max:
                row.append("D")
            else:
                row.append("E")

        block.append(row)

    f.append(block)

print(f)




[[['D', 'B', 'B', 'D', 'B'], ['B', 'D', 'D', 'D', 'B'], ['B', 'B', 'D', 'D', 'B']], [['B', 'D', 'D', 'E', 'D'], ['B', 'A', 'B', 'D', 'D'], ['D', 'B', 'D', 'D', 'B']]]
